#ifndef KEYBOARD_H
#define KEYBOARD_H

#define KEYBOARD_CONCAT(a, b) a ## b
#define KEYBOARD_CONCAT_EXPAND(a, b) KEYBOARD_CONCAT(a, b)

#define KEYBOARD_PORT_CODE D
#define KEYBOARD_CLOCK_PIN_NUM 3
#define KEYBOARD_DATA_PIN_NUM 4
#define KEYBOARD_INTERRUPT_NUM 1

#define KEYBOARD_PIN KEYBOARD_CONCAT_EXPAND(PIN, KEYBOARD_PORT_CODE)
#define KEYBOARD_PORT KEYBOARD_CONCAT_EXPAND(PORT, KEYBOARD_PORT_CODE)
#define KEYBOARD_INTERRUPT KEYBOARD_CONCAT_EXPAND(INT, KEYBOARD_INTERRUPT_NUM)
#define KEYBOARD_INTERRUPT_PREFIX KEYBOARD_CONCAT_EXPAND(ISC, KEYBOARD_INTERRUPT_NUM)
#define KEYBOARD_INTERRUPT_CTRL KEYBOARD_CONCAT_EXPAND(KEYBOARD_INTERRUPT_PREFIX, 1)

#define KEYBOARD_INTERRUPT_SUFFIX KEYBOARD_CONCAT_EXPAND(KEYBOARD_INTERRUPT_NUM, _vect)
#define KEYBOARD_INTERRUPT_VECTOR KEYBOARD_CONCAT_EXPAND(INT, KEYBOARD_INTERRUPT_SUFFIX)

#define read_keyboard_data() (KEYBOARD_PIN & (1 << KEYBOARD_DATA_PIN_NUM) ? 1 : 0)
#define setup_keyboard_interrupt() ISR(KEYBOARD_INTERRUPT_VECTOR) { keyboard_interrupt(); }

void keyboard_init(void);

#endif
